protocol SupportOutput: Sendable {
    /// Configuration that determines the generated support declaration.
    var configuration: Configuration { get }

    /// Generated Swift declarations.
    var source: String { get }

    /// Top-level Swift types generated by this output.
    var topLevelTypeNames: [SwiftTypeIdentifier] { get }
}

extension SupportOutput {
    var accessLevel: String {
        configuration.output.support.accessLevel == .public ? "public " : ""
    }
}
